name: Docker Image CI added test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag docker-test:local

    - name: Run the Container
      id: run
      env:
        INPUT_WHO_TO_GREET: Mona Lisa Octocat
      run:
        docker run \
          --env INPUT_WHO_TO_GREET="${{ env.INPUT_WHO_TO_GREET }}" \
          --rm docker-test:local